### PR TITLE
Editing

### PR DESCRIPTION
**Pull request by SparkyTS**

### CODE REVIEW

**Comment by goxr3plus** [comment]
Hello my friend.

**Comment by goxr3plus** [comment]
Thank for pull requesting, 1 thing thought... please don't push `. class` files as we don't need them :)

I will merge now but remember for future :)

**Review by goxr3plus — APPROVED** [review]

**Comment by SparkyTS** [comment]
Yeah, right my bad.

**Comment by goxr3plus** [comment]
Can you fix it before i merge this actually :). We need quality.

**Comment by SparkyTS** [comment]
just deleted those unnecessary files.
now you can merge.

**Comment by goxr3plus** [comment]
Ready :)

**Pull request merged**
